# Q-1

B) RAINBOW

# Q-2

In [2]:
print("LETS UPGRADE")

LETS UPGRADE


# Q-3

In [7]:
cost_price = int(input("Enter cost price: "))
selling_price = int(input("Enter selling price: "))

if cost_price < selling_price:
    print("Profit")
elif cost_price > selling_price:
    print("Loss")
else:
    print("Neither")

Enter cost price: 90
Enter selling price: 190
Profit


# Q-4

In [9]:
e = int(input("Enter Euros: "))
print("Equivalent in Rupees is: ", e * 80)

Enter Euros: 72
Equivalent in Rupees is:  5760


# Q-5

In [10]:
lst = list()
for i in range(0,10):
    a = int(input())
    if a % 2 == 0:
        lst.append(a)

print(lst)

2
3
4
5
6
7
8
9
12
44
[2, 4, 6, 8, 12, 44]


# Q-6

# Q-7

In [15]:
n = int(input("Enter the number: "))
d = { }
for i in range(1, n + 1):
    d[i] = i * i
print(d)

Enter the number: 15
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}


# Q-8

In [20]:
import math

In [24]:
print(math.sqrt(4))
print(round(math.sqrt(5)))

2.0
2


In [30]:
n = int(input("Enter numeber of directions: "))
lst = ["UP","DOWN","LEFT","RIGHT"]
dict = { }
for i in range(0, n):
    print(lst[i], end = " ")
    a = int(input())
    dict[lst[i]] = a
Y = dict["UP"] - dict["DOWN"]
X = dict["RIGHT"] - dict["LEFT"]
print(round(math.sqrt(X * X + Y * Y)))

Enter numeber of directions: 4
UP 7
DOWN 8
LEFT 9
RIGHT 4
5


# Q-9

In [32]:
import numpy as np

In [34]:
arr = np.arange(2, 50, 3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Q-10

In [51]:
lst1 = []
lst2 = []

for i in range(5):
    n = int(input())
    lst1.append(n)

for j in range(5):
    m = int(input())
    lst2.append(m)
print("first list: ", lst1)
print("second list: ", lst2)
arr1 = np.array(lst1)
arr2 = np.array(lst2)
arr3 = np.concatenate((arr1, arr2))
print("After concatenation: ", arr3)
print("After sorted: " , np.sort((arr1, arr2)))

11
43
6
3
79
33
5
43
87
34
first list:  [11, 43, 6, 3, 79]
second list:  [33, 5, 43, 87, 34]
After concatenation:  [11 43  6  3 79 33  5 43 87 34]
After sorted:  [[ 3  6 11 43 79]
 [ 5 33 34 43 87]]


# Q-11

In [56]:
arr = np.array( [ [1, 2, 3], [45, 89, 98], [21, 34, 98] ] )
print(arr)
print(np.ndim(arr))
print(np.shape(arr))

[[ 1  2  3]
 [45 89 98]
 [21 34 98]]
2
(3, 3)


# Q-12

In [63]:
arr = np.arange(12)
print(arr)
print("----------------")
print(np.reshape(arr , (2, 6)))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


# Q-13 

In [68]:
arr1 = np.array( [ [12, 14], [15, 16]])
arr2 = np.array( [ [22, 24], [25, 26]])
print(np.vstack((arr1, arr2)))
print("-----------------")
print(np.hstack((arr1, arr2)))

[[12 14]
 [15 16]
 [22 24]
 [25 26]]
-----------------
[[12 14 22 24]
 [15 16 25 26]]


# Q-14

In [78]:
my_lst = ['Mon', 'Tue', 'Mon', 'wed', 40, 40, 'sat', 66, 76, 76, 66, 'sat', 'Tue']
lst = []
for i in my_lst:
    if i not in lst:
        lst.append(i)
print(lst)

['Mon', 'Tue', 'wed', 40, 'sat', 66, 76]
